name: CI/CT for each push

on:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.json'
      - '**/ci.yml'
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install dependencies 👨🏻‍💻
      run: yarn
    
    - name: E2E Test for Electron 🧪
      run: yarn test
   
    - name: Upload Test Results 🗃
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: screenshots-${{ matrix.os }}-${{ matrix.node-version }}
        path: tests/screenshots/**
        
